---
name: XML-CommonNS
version: 0.04
author:
  - 'Chris Prather <perigrin@cpan.org>'
abstract: A list of commonly used namespaces
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Test::More: 0
  version: 0
provides:
  XML::CommonNS:
    file: lib/XML/CommonNS.pm
    version: 0.04
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
